labels:
  ':rocket: Deploy to Production':
    environment: production
    description: Production deployment
  ':rocket: Deploy to Staging':
    environment: staging
    description: Staging deployment
  ':rocket: Deploy to Test':
    environment: test
    description: Test deployment
    transient_environment: true
    auto_merge: false
    payload: 
      port: 8080
      https: true
