labels:
  Deploy%20to%20Production:
    environment: production
    description: Production deployment
    production_environment: true
    required_contexts: ["Test", "Install"]
  Deploy%20to%20Staging:
    environment: staging
    description: Staging deployment
    transient_environment: false
    required_contexts: ["Test", "Install"]
  Deploy%20to%20Test:
    environment: test
    description: Test deployment
    transient_environment: true
    auto_merge: false
    required_contexts: []
    payload:
      port: 8080
      https: true
